spring:
  application:
    name: payment-service #Name that will be register in eureka server
  #Database Config
  datasource:
    url: jdbc:sqlserver://database:1433;databaseName=checkout_db
    username: admin
    password: ${DATABASE_PASSWD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #Hibernate Config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  #Rabbit MQ
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 15672
    username: admin
    password: admin
    exchange: payment.exchange
    queue: payment.queue
    routing-key: payment.routing-key
    template:
      reply-timeout: 60000

server:
  port: 8000
#Eureka Client Config
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {http://localhost:8761/eureka}

#Swagger Documentation
springdoc:
  swagger-ui:
    path: /checkout/swagger-ui.html

#Request Mapping
request:
  mapping:
    payment: /api/v1.0/checkout








