services:
  database:
    image: 'mcr.microsoft.com/azure-sql-edge'
    container_name: sql_server
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_SA_PASSWORD=my1Complex2P@ssword!'
    ports:
      - '1433:1433'
    networks:
      - database_net

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

    restart: always

networks:
  database_net:
